import type { History, Meta, ChainView, Status } from "../api.js";
import { count } from "../format.js";
import Num from "./Num.js";

const seconds = (ms: number) => `${(ms / 1000).toFixed(1)}s`;

const since = (at?: number) => {
  if (!at) return "";
  const hours = (Date.now() - at) / 3_600_000;
  if (hours < 1) return ` in ${Math.max(1, Math.round(hours * 60))} min`;
  if (hours < 48) return ` in ${Math.round(hours)} h`;
  return ` in ${Math.round(hours / 24)} days`;
};

export default function Live({
  history,
  chain,
  meta,
  status,
}: {
  history?: History;
  chain?: ChainView;
  meta?: Meta;
  status?: Status;
}) {
  const scan = status?.scan;
  // A restored wallet never scans, so a scan bar reading 0% would be a lie about
  // what is taking the time. Only show it once the scan is actually running.
  const scanning = (scan?.applied ?? 0) > 0;
  const percent = scan?.estimatedTotal
    ? (scan.applied / scan.estimatedTotal) * 100
    : 0;
  const remaining =
    scan?.secondsLeft && scan.secondsLeft > 90
      ? `${Math.round(scan.secondsLeft / 60)} min`
      : `${scan?.secondsLeft ?? 0}s`;

  const figures: { value: React.ReactNode; label: string }[] = [
    {
      value: history ? <Num value={history.transactions} /> : "—",
      label: `real transactions${since(history?.since)}`,
    },
    {
      value: history?.medianMs ? seconds(history.medianMs) : "—",
      label: "median to prove and confirm",
    },
    {
      value: chain ? <Num value={chain.retirementEvents} /> : "—",
      label: "retirements, tonnage never disclosed",
    },
    {
      value: chain ? <Num value={chain.transferEvents} /> : "—",
      label: "credits traded, counterparties hidden",
    },
    {
      value: history ? <Num value={history.refusals} /> : "—",
      label: "lies the circuit refused to prove",
    },
    {
      value: chain ? <Num value={chain.issuedTonnes} /> : "—",
      label: "tonnes issued, publicly auditable",
    },
  ];

  return (
    <section className="live-strip">
      <div className="live-head">
        <span className={`pill${status?.ready ? " live" : ""}`}>
          <span className={`dot${status?.ready ? " pulse" : ""}`} />
          {status?.ready ? "live" : "arming"}
        </span>
        <span className="live-where">
          Midnight {meta?.network ?? "preprod"}
          {meta?.contractAddress ? " · contract" : ""}
        </span>
        {meta?.contractAddress && (
          <code className="live-address">{meta.contractAddress}</code>
        )}
      </div>

      {meta?.contractAddress ? (
        <div className="live-figures">
          {figures.map((figure) => (
            <div key={figure.label} className="live-figure">
              <div className="live-value">{figure.value}</div>
              <div className="live-label">{figure.label}</div>
            </div>
          ))}
          <div className="live-figure live-foot">
            <div className="live-label">
              Measured on this deployment, not projected. Every one of these was
              a real transaction on Midnight {meta?.network ?? "preprod"}, and{" "}
              <strong>What it costs</strong> breaks them down per circuit
              alongside what the contract does and does not scale with.
            </div>
          </div>
        </div>
      ) : (
        <div className="scan">
          {scanning ? (
            <>
              <div className="scan-bar">
                <div
                  className="scan-fill"
                  style={{ width: `${Math.min(99, Math.round(percent))}%` }}
                />
              </div>
              <div className="scan-line">
                <span>
                  <strong>{Math.round(percent)}%</strong> —{" "}
                  {count(status?.scan?.applied ?? 0)} of about{" "}
                  {count(status?.scan?.estimatedTotal ?? 0)} ledger updates
                  replayed
                </span>
                <span>
                  {status?.scan?.perSecond
                    ? `${count(status.scan.perSecond)}/sec · about ${remaining} left`
                    : "starting up"}
                </span>
              </div>
              <div className="scan-note">
                Midnight pays transaction fees in DUST, which is generated by
                registered NIGHT and can only be found by replaying the ledger
                from genesis — PreProd is past 950,000 blocks and 5.1 million
                events. The total is an estimate taken from a previous completed
                scan. This runs once; the result is cached to disk, so every
                later restart takes seconds.
              </div>
            </>
          ) : (
            <>
              <div className="scan-line">
                <span>
                  <strong>{status?.stage ?? "starting up"}</strong>
                </span>
                <span>
                  {status?.stageSeconds
                    ? `${status.stageSeconds}s so far`
                    : "just started"}
                </span>
              </div>
              <div className="scan-note">
                No contract is being read yet, which means this deployment is
                still standing one up. Nothing on this page is cached or faked,
                so there is nothing to show until it exists.
              </div>
            </>
          )}
        </div>
      )}
    </section>
  );
}
