import type { History, Meta, ChainView, Status } from "../api.js";

const seconds = (ms: number) => `${(ms / 1000).toFixed(1)}s`;

const since = (at?: number) => {
  if (!at) return "";
  const hours = (Date.now() - at) / 3_600_000;
  if (hours < 1) return ` in ${Math.max(1, Math.round(hours * 60))} min`;
  if (hours < 48) return ` in ${Math.round(hours)} h`;
  return ` in ${Math.round(hours / 24)} days`;
};

export default function Live({
  history,
  chain,
  meta,
  status,
}: {
  history?: History;
  chain?: ChainView;
  meta?: Meta;
  status?: Status;
}) {
  const scan = status?.scan;
  const percent = scan?.estimatedTotal
    ? (scan.applied / scan.estimatedTotal) * 100
    : 0;
  const remaining =
    scan?.secondsLeft && scan.secondsLeft > 90
      ? `${Math.round(scan.secondsLeft / 60)} min`
      : `${scan?.secondsLeft ?? 0}s`;

  const figures = [
    {
      value: history ? history.transactions.toLocaleString() : "—",
      label: `real transactions${since(history?.since)}`,
    },
    {
      value: history?.medianMs ? seconds(history.medianMs) : "—",
      label: "median prove and confirm",
    },
    {
      value: chain ? Number(chain.issuedTonnes).toLocaleString() : "—",
      label: "tonnes issued, publicly",
    },
    {
      value: chain ? chain.retirementEvents.toLocaleString() : "—",
      label: "retirements, tonnage hidden",
    },
    {
      value: history ? history.rejections.toLocaleString() : "—",
      label: "fraud attempts refused",
    },
  ];

  return (
    <section className="live-strip">
      <div className="live-head">
        <span className={`pill${status?.ready ? " live" : ""}`}>
          <span className={`dot${status?.ready ? " pulse" : ""}`} />
          {status?.ready ? "live" : "arming"}
        </span>
        <span className="live-where">
          Midnight {meta?.network ?? "preprod"}
          {meta?.contractAddress ? " · contract" : ""}
        </span>
        {meta?.contractAddress && (
          <code className="live-address">{meta.contractAddress}</code>
        )}
      </div>

      {meta?.contractAddress ? (
        <div className="live-figures">
          {figures.map((figure) => (
            <div key={figure.label} className="live-figure">
              <div className="live-value">{figure.value}</div>
              <div className="live-label">{figure.label}</div>
            </div>
          ))}
        </div>
      ) : (
        <div className="scan">
          <div className="scan-bar">
            <div
              className="scan-fill"
              style={{ width: `${Math.min(99, Math.round(percent))}%` }}
            />
          </div>
          <div className="scan-line">
            <span>
              <strong>{Math.round(percent)}%</strong> —{" "}
              {(status?.scan?.applied ?? 0).toLocaleString()} of about{" "}
              {(status?.scan?.estimatedTotal ?? 0).toLocaleString()} ledger
              updates replayed
            </span>
            <span>
              {status?.scan?.perSecond
                ? `${status.scan.perSecond.toLocaleString()}/sec · about ${remaining} left`
                : "starting up"}
            </span>
          </div>
          <div className="scan-note">
            Midnight pays transaction fees in DUST, which is generated by
            registered NIGHT and can only be found by replaying the ledger from
            genesis — PreProd is past 950,000 blocks and 5.1 million events. The
            total is an estimate taken from a previous completed scan. This runs
            once; the result is cached to disk, so every later restart takes
            seconds.
          </div>
        </div>
      )}
    </section>
  );
}
